sudo: required
services:
  - docker

before_install:
  - docker build -t nikhil434/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run nikhil434/react-test npm test -- --coverage

after_success:
  - docker build -t nikhil434/multi_client ./client
  - docker build -t nikhil434/multi_server ./server
  - docker build -t nikhil434/multi_nginx ./nginx
  - docker build -t nikhil434/multi_worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push nikhil434/multi-client
  - docker push nikhil434/multi-nginx
  - docker push nikhil434/multi-server
  - docker push nikhil434/multi-worker
